plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace 'com.example.cardifyocrner'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.cardifyocrner"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"

        aaptOptions {
            noCompress "tflite"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.8.0"
    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'com.google.android.material:material:1.7.0'

    implementation 'com.google.mlkit:text-recognition:16.0.0'

    implementation 'org.tensorflow:tensorflow-lite:2.13.0'
    implementation 'org.tensorflow:tensorflow-lite-support:0.4.4'
}
